# Generated by Django 3.2.12 on 2022-06-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='thumbnails/'),
        ),
    ]
