# Generated by Django 3.2.12 on 2022-06-16 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
