# Generated by Django 3.2.12 on 2022-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contect',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
