# Generated by Django 3.2.12 on 2022-05-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contect_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contect',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
